#ifndef __DEF_H__
#define __DEF_H__


#define BAGGING_SIZE 1
#define BOOSTING_SIZE 5
#define MAX_LEAVES 32
#define MAX_DEPTH 7
#define LEARNING_RATE 1.0
#define FEATURE_NUMBER 201
#define FEATURE_NUM_FOR_TRAIN 201
#define TRAINING_SET_SIZE 1866819
#define TRAINING_SET_SIZE_FOR_TRAIN 100000
#define TRAINING_FRACTION 0.1
#define TESTING_SET_SIZE 282796
#define SCATTER_RATIO 2.0

#endif
