#ifndef __DEF_H__
#define __DEF_H__

#define FEATURE_FRACTION 0.8
#define BAGGING_FRACTION 0.8
#define BOOSTING_SIZE 2
#define MAX_LEAVES 32
#define MAX_DEPTH 7
#define LEARNING_RATE 1.0
#define FEATURE_NUMBER 201
#define TRAINING_SET_SIZE 1866819
#define TESTING_SET_SIZE 282796

#endif
